insert into station (id, state, name, latitude, longitude) values ('KATL','GA','Hartsfield-Jackson/Atlanta International Airport',33.66,-84.42);
insert into station (id, state, name, latitude, longitude) values ('KBOS','MA','Boston, Logan International Airport',42.38,-71.03);
insert into station (id, state, name, latitude, longitude) values ('KBWI','MD','Baltimore-Washington International Airport',39.19,-76.67);
insert into station (id, state, name, latitude, longitude) values ('KCLE','OH','Cleveland-Hopkins International Airport',41.42,-81.85);
insert into station (id, state, name, latitude, longitude) values ('KCLT','NC','Charlotte/Douglas International Airport',35.21,-80.94);
insert into station (id, state, name, latitude, longitude) values ('KCVG','KY','Covington / Cincinnati / Northern Kentucky',39.05,-84.67);
insert into station (id, state, name, latitude, longitude) values ('KDCA','VA','Washington DC, Reagan National Airport',38.86,-77.03);
insert into station (id, state, name, latitude, longitude) values ('KDEN','CO','Denver Intnl Arpt',39.87,-104.67);
insert into station (id, state, name, latitude, longitude) values ('KDFW','TX','Dallas / Fort Worth International Airport',32.91,-97.03);
insert into station (id, state, name, latitude, longitude) values ('KDTW','MI','Detroit Metropolitan Wayne County Airport',42.23,-83.33);
insert into station (id, state, name, latitude, longitude) values ('KEWR','NJ','Newark International Airport',40.71,-74.17);
insert into station (id, state, name, latitude, longitude) values ('KFLL','FL','Fort Lauderdale / Hollywood Intl Airport',26.07,-80.15);
insert into station (id, state, name, latitude, longitude) values ('KIAD','VA','Washington-Dulles International Airport',38.96,-77.45);
insert into station (id, state, name, latitude, longitude) values ('KUKI','CA','Ukiah Muni (awos)',39.14,-123.2);
insert into station (id, state, name, latitude, longitude) values ('KJFK','NY','New York/John F. Kennedy Intl Airport',40.66,-73.78);
insert into station (id, state, name, latitude, longitude) values ('KLAS','NV','Las Vegas/Mccarran',36.0789,-115.155);
insert into station (id, state, name, latitude, longitude) values ('KLAX','CA','Los Angeles Intl Airport',33.94,-118.4);
insert into station (id, state, name, latitude, longitude) values ('KLGA','NY','New York, La Guardia Airport',40.78,-73.88);
insert into station (id, state, name, latitude, longitude) values ('KMCO','FL','Orlando International Airport',28.43,-81.32);
insert into station (id, state, name, latitude, longitude) values ('KMDW','IL','Chicago Midway Airport',41.79,-87.75);
insert into station (id, state, name, latitude, longitude) values ('KMEM','TN','Memphis International Airport',35.04,-89.98);
insert into station (id, state, name, latitude, longitude) values ('KMIA','FL','Miami International Airport',25.78,-80.32);
insert into station (id, state, name, latitude, longitude) values ('KMSP','MN','Minneapolis-St. Paul International Airport',44.89,-93.22);
insert into station (id, state, name, latitude, longitude) values ('KORD','IL','Chicago/O''Hare',41.98,-87.9);
insert into station (id, state, name, latitude, longitude) values ('KPDX','OR','Portland Intl Arpt',45.58,-122.6);
insert into station (id, state, name, latitude, longitude) values ('KPHL','PA','Philadelphia International Airport',39.87,-75.23);
insert into station (id, state, name, latitude, longitude) values ('KPHX','AZ','Phoenix/Sky Harbor',33.44,-112.02);
insert into station (id, state, name, latitude, longitude) values ('KPIT','PA','Pittsburgh International Airport',40.51,-80.22);
insert into station (id, state, name, latitude, longitude) values ('KSAN','CA','San Diego/Lindbergh',32.73,-117.17);
insert into station (id, state, name, latitude, longitude) values ('KSEA','WA','Seattle-Tacoma Intl Airport',47.44,-122.31);
insert into station (id, state, name, latitude, longitude) values ('KSFO','CA','San Francisco Intl Airport',37.62,-122.37);
insert into station (id, state, name, latitude, longitude) values ('KSLC','UT','Salt Lake City International',40.79,-111.97);
insert into station (id, state, name, latitude, longitude) values ('KSTL','MO','Lambert-St. Louis International Airport',38.76,-90.37);
insert into station (id, state, name, latitude, longitude) values ('KTPA','FL','Tampa International Airport',27.97,-82.53);
